name: Publish NPM package
run-name: Publish PR Version

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  pre_publish: 
    name: Pre-Publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps: 
      # - name: Say Hello
      #   run: sleep 15;

      - name: Say Hello
        run: echo "Hello World!"

  publish_npm:
    name: Publish package
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: pre_publish
    
    if: contains(github.event.pull_request.labels.*.name, 'pr deploy') || github.event_name == 'push'

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          # ref: 
      - name: git log
        run: git log
