name: Hello World
run-name: Hello ${{ inputs.name }}

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      agent: 
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  print:
    name: Print message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format agent name
        if: ${{ inputs.agent != '' }}
        run: echo "AGENT_MESSAGE="Agent is ${{ inputs.agent }}"" >> $GITHUB_OUTPUT
        id: format_agent
      
      - name: Print agent message
        if: ${{ steps.format_agent.outputs.AGENT_MESSAGE != '' }}
        run: echo ${{ steps.format_agent.outputs.AGENT_MESSAGE }}
        
      - name: print
        run: |
          echo "Hello ${{ inputs.name }}"
          node -v