name: Hello World
run-name: Hello ${{ inputs.name }}

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  print:
    name: Print message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve node version
        run: |
          echo "NODE_VERSION=$(cat package.json | jq -r .engines.node)" >> $GITHUB_OUTPUT
        id: node_version

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: print
        run: |
          echo "Hello ${{ inputs.name }}"
          node -v